// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*App, error) {
	config, err := providerConfig(ctx)
	if err != nil {
		return nil, err
	}
	app := &App{
		Config: config,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config *Config
}
